name: build

on:
  push:
  workflow_dispatch:
    branches: [ master, test ]

jobs:
  build:

    name: build-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: install winser on windows
      if: runner.os == 'Windows'
      run: npm install winser -g
      
    - name: Mirakurun install
      run: npm install mirakurun@latest -g --foreground-scripts --production

    - name: Install all
      run: npm run all-install
      
    - name: Build
      run: npm run build

    - name: Compress Project
      run: |
        7z a -m0=LZMA2 -mx=9 -md=128m -mfb=128 -ms=16g -mmt=on -mf=BCJ ${{ matrix.os }}-${{ matrix.node-version }}.7z ../EPGStation

    - name: Upload Project as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.os }}-${{ matrix.node-version }}.7z
        path: ${{ matrix.os }}-${{ matrix.node-version }}.7z